services:

  postgres:
    image: postgres:16
    container_name: taskmanager-postgres

    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5437:5432"

    volumes:
      - docker_postgres_data:/var/lib/postgresql/data


  backend:
    image: task-manager-backend:latest
    container_name: task-manager-backend

    ports:
      - "8090:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend
    container_name: task-manager-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend


volumes:
  docker_postgres_data:
    external: true